package edu.umg.ventasonline.bean;
// Generated Oct 10, 2016 8:05:33 PM by Hibernate Tools 4.3.1



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {
     private Integer idCliente;
     private Departamento departamento;
     private Profesion profesion;
     private Pais pais;
     private TipoDocumento tipoDocumento;
     private String numeroDocumento;
     private String nombreCompleto;
     private String telefonoResidencia;
     private String telefonoCelular;
     private String direccion;
     private String residencia;
     private Usuario usuario;

    public Cliente() {
    }

	
    public Cliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public Cliente(Integer idCliente, Departamento departamento, Profesion profesion, Pais pais, TipoDocumento tipoDocumento, String numeroDocumento, String nombreCompleto, String telefonoResidencia, String telefonoCelular, String direccion, String residencia, Usuario usuario) {
       this.idCliente = idCliente;
       this.departamento = departamento;
       this.profesion = profesion;
       this.pais = pais;
       this.tipoDocumento = tipoDocumento;
       this.numeroDocumento = numeroDocumento;
       this.nombreCompleto = nombreCompleto;
       this.telefonoResidencia = telefonoResidencia;
       this.telefonoCelular = telefonoCelular;
       this.direccion = direccion;
       this.residencia = residencia;
       this.usuario = usuario;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public Profesion getProfesion() {
        return this.profesion;
    }
    
    public void setProfesion(Profesion profesion) {
        this.profesion = profesion;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public TipoDocumento getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(TipoDocumento tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public String getTelefonoResidencia() {
        return this.telefonoResidencia;
    }
    
    public void setTelefonoResidencia(String telefonoResidencia) {
        this.telefonoResidencia = telefonoResidencia;
    }
    public String getTelefonoCelular() {
        return this.telefonoCelular;
    }
    
    public void setTelefonoCelular(String telefonoCelular) {
        this.telefonoCelular = telefonoCelular;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getResidencia() {
        return this.residencia;
    }
    
    public void setResidencia(String residencia) {
        this.residencia = residencia;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


