package edu.umg.ventasonline.bean;
// Generated Oct 10, 2016 8:05:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private Integer idDepartamento;
     private String nombre;
     private Set clientes = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public Departamento(Integer idDepartamento, String nombre, Set clientes) {
       this.idDepartamento = idDepartamento;
       this.nombre = nombre;
       this.clientes = clientes;
    }
   
    public Integer getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


