package edu.umg.ventasonline.bean;
// Generated Oct 10, 2016 8:05:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * FacturaD generated by hbm2java
 */
public class FacturaD  implements java.io.Serializable {


     private BigDecimal idFacturaD;
     private FacturaH facturaH;
     private Producto producto;
     private BigDecimal noLinea;
     private BigDecimal cantidad;
     private BigDecimal monto;

    public FacturaD() {
    }

	
    public FacturaD(BigDecimal idFacturaD) {
        this.idFacturaD = idFacturaD;
    }
    public FacturaD(BigDecimal idFacturaD, FacturaH facturaH, Producto producto, BigDecimal noLinea, BigDecimal cantidad, BigDecimal monto) {
       this.idFacturaD = idFacturaD;
       this.facturaH = facturaH;
       this.producto = producto;
       this.noLinea = noLinea;
       this.cantidad = cantidad;
       this.monto = monto;
    }
   
    public BigDecimal getIdFacturaD() {
        return this.idFacturaD;
    }
    
    public void setIdFacturaD(BigDecimal idFacturaD) {
        this.idFacturaD = idFacturaD;
    }
    public FacturaH getFacturaH() {
        return this.facturaH;
    }
    
    public void setFacturaH(FacturaH facturaH) {
        this.facturaH = facturaH;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public BigDecimal getNoLinea() {
        return this.noLinea;
    }
    
    public void setNoLinea(BigDecimal noLinea) {
        this.noLinea = noLinea;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }




}


