package edu.umg.ventasonline.bean;
// Generated Oct 10, 2016 8:05:33 PM by Hibernate Tools 4.3.1



/**
 * FacturaD generated by hbm2java
 */
public class FacturaD  implements java.io.Serializable {


     private Integer idFacturaD;
     private FacturaH facturaH;
     private Producto producto;
     private Integer noLinea;
     private Integer cantidad;
     private Integer monto;

    public FacturaD() {
    }

	
    public FacturaD(Integer idFacturaD) {
        this.idFacturaD = idFacturaD;
    }
    public FacturaD(Integer idFacturaD, FacturaH facturaH, Producto producto, Integer noLinea, Integer cantidad, Integer monto) {
       this.idFacturaD = idFacturaD;
       this.facturaH = facturaH;
       this.producto = producto;
       this.noLinea = noLinea;
       this.cantidad = cantidad;
       this.monto = monto;
    }
   
    public Integer getIdFacturaD() {
        return this.idFacturaD;
    }
    
    public void setIdFacturaD(Integer idFacturaD) {
        this.idFacturaD = idFacturaD;
    }
    public FacturaH getFacturaH() {
        return this.facturaH;
    }
    
    public void setFacturaH(FacturaH facturaH) {
        this.facturaH = facturaH;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Integer getNoLinea() {
        return this.noLinea;
    }
    
    public void setNoLinea(Integer noLinea) {
        this.noLinea = noLinea;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Integer getMonto() {
        return this.monto;
    }
    
    public void setMonto(Integer monto) {
        this.monto = monto;
    }




}


