package edu.umg.ventasonline.bean;
// Generated Oct 10, 2016 8:05:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FacturaH generated by hbm2java
 */
public class FacturaH  implements java.io.Serializable {


     private Integer idFacturaH;
     private FormaPago formaPago;
     private Integer idCliente;
     private String nombre;
     private String direccion;
     private Date fecha;
     private Set facturaDs = new HashSet(0);

    public FacturaH() {
    }

	
    public FacturaH(Integer idFacturaH) {
        this.idFacturaH = idFacturaH;
    }
    public FacturaH(Integer idFacturaH, FormaPago formaPago, Integer idCliente, String nombre, String direccion, Date fecha, Set facturaDs) {
       this.idFacturaH = idFacturaH;
       this.formaPago = formaPago;
       this.idCliente = idCliente;
       this.nombre = nombre;
       this.direccion = direccion;
       this.fecha = fecha;
       this.facturaDs = facturaDs;
    }
   
    public Integer getIdFacturaH() {
        return this.idFacturaH;
    }
    
    public void setIdFacturaH(Integer idFacturaH) {
        this.idFacturaH = idFacturaH;
    }
    public FormaPago getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(FormaPago formaPago) {
        this.formaPago = formaPago;
    }
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getFacturaDs() {
        return this.facturaDs;
    }
    
    public void setFacturaDs(Set facturaDs) {
        this.facturaDs = facturaDs;
    }




}


