package edu.umg.ventasonline.bean;
// Generated Oct 10, 2016 8:05:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FormaPago generated by hbm2java
 */
public class FormaPago  implements java.io.Serializable {


     private Integer idFormaPago;
     private TipoPago tipoPago;
     private Integer noLinea;
     private Integer monto;
     private String numero;
     private Integer autorizacion;
     private Set facturaHs = new HashSet(0);

    public FormaPago() {
    }

	
    public FormaPago(Integer idFormaPago) {
        this.idFormaPago = idFormaPago;
    }
    public FormaPago(Integer idFormaPago, TipoPago tipoPago, Integer noLinea, Integer monto, String numero, Integer autorizacion, Set facturaHs) {
       this.idFormaPago = idFormaPago;
       this.tipoPago = tipoPago;
       this.noLinea = noLinea;
       this.monto = monto;
       this.numero = numero;
       this.autorizacion = autorizacion;
       this.facturaHs = facturaHs;
    }
   
    public Integer getIdFormaPago() {
        return this.idFormaPago;
    }
    
    public void setIdFormaPago(Integer idFormaPago) {
        this.idFormaPago = idFormaPago;
    }
    public TipoPago getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(TipoPago tipoPago) {
        this.tipoPago = tipoPago;
    }
    public Integer getNoLinea() {
        return this.noLinea;
    }
    
    public void setNoLinea(Integer noLinea) {
        this.noLinea = noLinea;
    }
    public Integer getMonto() {
        return this.monto;
    }
    
    public void setMonto(Integer monto) {
        this.monto = monto;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public Integer getAutorizacion() {
        return this.autorizacion;
    }
    
    public void setAutorizacion(Integer autorizacion) {
        this.autorizacion = autorizacion;
    }
    public Set getFacturaHs() {
        return this.facturaHs;
    }
    
    public void setFacturaHs(Set facturaHs) {
        this.facturaHs = facturaHs;
    }




}


