package edu.umg.ventasonline.bean;
// Generated Oct 10, 2016 8:05:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * FormaPago generated by hbm2java
 */
public class FormaPago  implements java.io.Serializable {


     private BigDecimal idFormaPago;
     private TipoPago tipoPago;
     private BigDecimal noLinea;
     private BigDecimal monto;
     private String numero;
     private BigDecimal autorizacion;
     private Set facturaHs = new HashSet(0);

    public FormaPago() {
    }

	
    public FormaPago(BigDecimal idFormaPago) {
        this.idFormaPago = idFormaPago;
    }
    public FormaPago(BigDecimal idFormaPago, TipoPago tipoPago, BigDecimal noLinea, BigDecimal monto, String numero, BigDecimal autorizacion, Set facturaHs) {
       this.idFormaPago = idFormaPago;
       this.tipoPago = tipoPago;
       this.noLinea = noLinea;
       this.monto = monto;
       this.numero = numero;
       this.autorizacion = autorizacion;
       this.facturaHs = facturaHs;
    }
   
    public BigDecimal getIdFormaPago() {
        return this.idFormaPago;
    }
    
    public void setIdFormaPago(BigDecimal idFormaPago) {
        this.idFormaPago = idFormaPago;
    }
    public TipoPago getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(TipoPago tipoPago) {
        this.tipoPago = tipoPago;
    }
    public BigDecimal getNoLinea() {
        return this.noLinea;
    }
    
    public void setNoLinea(BigDecimal noLinea) {
        this.noLinea = noLinea;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public BigDecimal getAutorizacion() {
        return this.autorizacion;
    }
    
    public void setAutorizacion(BigDecimal autorizacion) {
        this.autorizacion = autorizacion;
    }
    public Set getFacturaHs() {
        return this.facturaHs;
    }
    
    public void setFacturaHs(Set facturaHs) {
        this.facturaHs = facturaHs;
    }




}


