package edu.umg.ventasonline.bean;
// Generated Oct 10, 2016 8:05:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private BigDecimal idPais;
     private String nombre;
     private Set clientes = new HashSet(0);

    public Pais() {
    }

	
    public Pais(BigDecimal idPais) {
        this.idPais = idPais;
    }
    public Pais(BigDecimal idPais, String nombre, Set clientes) {
       this.idPais = idPais;
       this.nombre = nombre;
       this.clientes = clientes;
    }
   
    public BigDecimal getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(BigDecimal idPais) {
        this.idPais = idPais;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


