package edu.umg.ventasonline.bean;
// Generated Oct 10, 2016 8:05:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Profesion generated by hbm2java
 */
public class Profesion  implements java.io.Serializable {


     private BigDecimal idProfesion;
     private String nombre;
     private Set clientes = new HashSet(0);

    public Profesion() {
    }

	
    public Profesion(BigDecimal idProfesion) {
        this.idProfesion = idProfesion;
    }
    public Profesion(BigDecimal idProfesion, String nombre, Set clientes) {
       this.idProfesion = idProfesion;
       this.nombre = nombre;
       this.clientes = clientes;
    }
   
    public BigDecimal getIdProfesion() {
        return this.idProfesion;
    }
    
    public void setIdProfesion(BigDecimal idProfesion) {
        this.idProfesion = idProfesion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


