package edu.umg.ventasonline.bean;
// Generated Oct 10, 2016 8:05:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoPago generated by hbm2java
 */
public class TipoPago  implements java.io.Serializable {


     private Integer idTipoPago;
     private String nombre;
     private Set formaPagos = new HashSet(0);

    public TipoPago() {
    }

	
    public TipoPago(Integer idTipoPago) {
        this.idTipoPago = idTipoPago;
    }
    public TipoPago(Integer idTipoPago, String nombre, Set formaPagos) {
       this.idTipoPago = idTipoPago;
       this.nombre = nombre;
       this.formaPagos = formaPagos;
    }
   
    public Integer getIdTipoPago() {
        return this.idTipoPago;
    }
    
    public void setIdTipoPago(Integer idTipoPago) {
        this.idTipoPago = idTipoPago;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getFormaPagos() {
        return this.formaPagos;
    }
    
    public void setFormaPagos(Set formaPagos) {
        this.formaPagos = formaPagos;
    }




}


